### PR TITLE
H5Easy: Support for n-d vector

### PR DESCRIPTION
**Pull request by tdegeus**
H5Easy read/write support for n-d vector. 

Supersedes #187 . 

Reading of n-d vector should work after merging #191 (relevant test should be uncommented then).

### CODE REVIEW

**Comment by tdegeus** [comment]
@adevress Are there existing functions for the following support functions that I introduced: `H5Easy::detail::vector::checkShape`, `H5Easy::detail::vector::getShape`, `H5Easy::detail::vector::fillShape` ?

**Comment by tdegeus** [comment]
@adevress Never mind, I simply tried... By removing also this the implementation is I think much more clean than before, and more generic too.

**Comment by ferdonline** [comment]
@tdegeus could we uncomment the tests?

**Comment by tdegeus** [comment]
@ferdonline Done! Looks like everything is good to go.

**Pull request merged**
