### PR TITLE
Release 2.3

### PR DESCRIPTION
**Pull request by tdegeus**
It has been a while since there was a release!

### CODE REVIEW

**Review by alkino — DISMISSED** [review]

**Comment by tdegeus** [comment]
Thanks @alkino . I bumped also the version in the `CMakeList.txt`. If you approve I can merge and release.

**Comment by tdegeus** [comment]
In my opinion it could be good the reformat the entire file. Currently it is not respecting the markdown in the sense that it is interpreted as code block

**Comment by ferdonline** [comment]
I'd like to wait until integration tests are merged. I'm afraid API compatibility was also broken WRT default constructors of objects, which we need to check before the release.

**Comment by ferdonline** [comment]
Btw, after so much development, I don't think this is a patch release, there are definitely new features.

**Comment by tdegeus** [comment]
> I'd like to wait until integration tests are merged. I'm afraid API compatibility was also broken WRT default constructors of objects, which we need to check before the release.

As you wish. However, I would prefer it'd be quite soon though. Some patches are quite old and conda-forge users, like me, are still not able to use them

**Comment by ferdonline** [comment]
To speed up releasing 2.3 feel free to review #431 and #434

**Comment by ferdonline** [comment]
WIP: see https://github.com/BlueBrain/HighFive/milestone/3

**Comment by ohm314** [comment]
BBP Integration tests are passing: https://github.com/BlueBrain/HighFive-testing/actions/runs/798222182

**Review by matz-e — APPROVED** [review]

**Comment by tdegeus** [comment]
Good to go?

**Comment by ohm314** [comment]
sorry.. forgot to update version in changelog. i think once everything passes, we can merge and tag.

**Review by matz-e — APPROVED** [review]

**Pull request merged**
