### PR TITLE
Unify interface of H5Attribute with H5Slice_traits

### PR DESCRIPTION
**Pull request by alkino**

### CODE REVIEW

**Review by matz-e — COMMENTED** [review]
So no data conversion for raw operations?

**Comment by alkino** [comment]
> So no data conversion for raw operations?
What do you mean, it's here only for `read_raw` (called `read(T*)`) and `write_raw`.

**Comment by ferdonline** [comment]
This kinda addresses #285, right? they use the same API, although they don't share code (yet!) :)

**Comment by alkino** [comment]
This patch was extracted from #366 to simplify it.

The next patch is #366 and deduplicate most things.

**Review by ferdonline — APPROVED** [review]

**Pull request merged**
