### PR TITLE
Enh/clang format

### PR DESCRIPTION
**Pull request by tristan0x**
This PR formats the C++ source code according to BBP HPC coding style. It also add a git submodule https://github.com/tristan0x/git-cmake-format to help keeping source code formatted.

### CODE REVIEW

**Comment by tristan0x** [comment]
@adevress Would you be interested by this one ?

**Comment by hernando** [comment]
I just rebased my copy of HighFive and noticed this PR.

Something that should be changed in my opinion is the dependency on a user repository: git-cmake-format should be forked in BlueBrain, not pulled from Tristan's fork.

**Comment by adevress** [comment]
I agree even if it is optional for HighFive. 
@tristan0x  Tristan do you mind to request a repository to Support for your git-cmake-format to put it under BlueBrain organisation ?

**Comment by tristan0x** [comment]
The repository has been requested

**Pull request merged**
