### PR TITLE
Const correctness for pointer decay

### PR DESCRIPTION
**Pull request by PhilipDeegan**
const correctness for pointer decay

**Description**

resolves the case where a const 1d vector is used for 2 or 3d datasets

error
```
In file included from include/highfive/H5DataType.hpp:369,
                 from include/highfive/H5DataSet.hpp:15,
                 from cpp.cpp:5:
include/highfive/bits/H5DataType_misc.hpp: In instantiation of ‘HighFive::AtomicType<T>::AtomicType() [with T = const double*]’:
include/highfive/bits/H5DataType_misc.hpp:400:12:   required from ‘HighFive::DataType HighFive::create_datatype() [with T = const double*]’
include/highfive/bits/H5ReadWrite_misc.hpp:83:39:   required from ‘HighFive::details::BufferInfo<T>::BufferInfo(const HighFive::DataType&) [with T = const double* const*]’
include/highfive/bits/H5Slice_traits_misc.hpp:203:34:   required from ‘void HighFive::SliceTraits<Derivate>::write(const T&) [with T = const double* const*; Derivate = HighFive::DataSet]’
cpp.cpp:53:22:   required from ‘void f() [with Data = double; long unsigned int dim = 2]’
cpp.cpp:86:18:   required from here
include/highfive/bits/H5DataType_misc.hpp:182:57: error: static assertion failed: Atomic types cant be arrays, except for char[] (fixed-length strings)
  182 |     static_assert(details::inspector<T>::recursive_ndim == 0,
      |                                          ~~~~~~~~~~~~~~~^~~~
include/highfive/bits/H5DataType_misc.hpp: In instantiation of ‘HighFive::AtomicType<T>::AtomicType() [with T = const double* const*]’:
include/highfive/bits/H5DataType_misc.hpp:400:12:   required from ‘HighFive::DataType HighFive::create_datatype() [with T = const double* const*]’
include/highfive/bits/H5ReadWrite_misc.hpp:83:39:   required from ‘HighFive::details::BufferInfo<T>::BufferInfo(const HighFive::DataType&) [with T = const double* const* const*]’
include/highfive/bits/H5Slice_traits_misc.hpp:203:34:   required from ‘void HighFive::SliceTraits<Derivate>::write(const T&) [with T = const double* const* const*; Derivate = HighFive::DataSet]’
cpp.cpp:53:22:   required from ‘void f() [with Data = double; long unsigned int dim = 3]’
cpp.cpp:88:18:   required from here
include/highfive/bits/H5DataType_misc.hpp:182:57: error: static assertion failed: Atomic types cant be arrays, except for char[] (fixed-length strings)
```

modified highfive example to support the notion.

```c++
#include <iostream>
#include <string>
#include <vector>

#include <highfive/H5DataSet.hpp>
#include <highfive/H5DataSpace.hpp>
#include <highfive/H5File.hpp>

const std::string FILE_NAME("create_extensible_dataset_example.h5");
const std::string DATASET_NAME("dset");

template<std::size_t dim, typename Data>
static auto pointer_dim_caster(Data* data)
{
    if constexpr (dim == 2)
        return reinterpret_cast<Data const* const* const>(data);
    if constexpr (dim == 3)
        return reinterpret_cast<Data const* const* const* const>(data);
}

template<std::size_t dim = 2>
static std::size_t size()
{
    if constexpr (dim == 2)
        return dim * dim;
    if constexpr (dim == 3)
        return dim * dim * dim;
}

template<typename Data, std::size_t dim = 2>
static auto vector()
{
    if constexpr (dim == 2)
        return std::vector<std::vector<Data>>{};
    if constexpr (dim == 3)
        return std::vector<std::vector<std::vector<Data>>>{};
}

template<typename Data, std::size_t dim = 2>
void f()
{
    using namespace HighFive;
    try
    {
        File file(FILE_NAME, File::ReadWrite | File::Create | File::Truncate);

        std::vector<std::size_t> shape(dim, dim);
        DataSpace dataspace = DataSpace(shape);

        DataSet dataset = file.createDataSet<double>(DATASET_NAME, dataspace);

        std::vector<double> const t1(size<dim>(), 1);
        dataset.write(pointer_dim_caster<dim>(t1.data()));

        auto result = vector<Data, dim>();
        dataset.read(result);

        if constexpr (dim == 2)
            for (auto row : result)
            {
                for (auto col : row)
                    std::cout << " " << col;
                std::cout << std::endl;
            }

        if constexpr (dim == 3)
            for (auto slab : result)
            {
                for (auto row : slab)
                {
                    for (auto col : row)
                        std::cout << " " << col;
                    std::cout << std::endl;
                }
                std::cout << std::endl;
            }
    }
    catch (const Exception& err)
    {
        std::cerr << err.what() << std::endl;
    }
}

int main(void)
{
    f<double, 2>();
    std::cout << std::endl;
    f<double, 3>();
    return 0;
}
```

compiler version
```bash
g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 10.2.1-6' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-10-Km9U7s/gcc-10-10.2.1/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-10-Km9U7s/gcc-10-10.2.1/debian/tmp-gcn/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-mutex
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20210110 (Debian 10.2.1-6)
```

system
```bash
uname -a
Linux fad 5.10.0-6-amd64 #1 SMP Debian 5.10.28-1 (2021-04-09) x86_64 GNU/Linux
```

### CODE REVIEW

**Comment by PhilipDeegan** [comment]
oh perhaps I should be using "write_raw" here?

**Comment by PhilipDeegan** [comment]
> @PhilipDeegan could you please also add a test which would fail otherwise?

Is the example I posted sufficient?

**Comment by ferdonline** [comment]
Anything as short as possible as a unit test :)

**Comment by PhilipDeegan** [comment]
I added a minimized version of the posted example above as an example, it's a compile time error so I didn't see it really as a unit test.

while setting it up I noticed that non-const pointers were not working with the modification, so I made a subclass of the inspector instead to support const and non-const pointers

**Comment by ferdonline** [comment]
> while setting it up I noticed that non-const pointers were not working with the modification, so I made a subclass of the inspector instead to support const and non-const pointers

Awesome. We are afraid of those kind of regressions. Your current solution looks nice. 

As for the example, well, I still think we should go into unit tests. Previously being a compilation error is not relevant IMO, actually if we get a compilation error right away when building the unit tests is a great check!

**Comment by ferdonline** [comment]
@PhilipDeegan I opened a PR for this branch to change your test file into an unit test.
Shall you accept that I'm happy with the change.

**Review by ferdonline — APPROVED** [review]

**Comment by ferdonline** [comment]
@alkino Do you agree with the current solution?

**Review by alkino — APPROVED** [review]

**Comment by alkino** [comment]
Sorry for being long

**Pull request merged**
