### PR TITLE
Add a single include file

### PR DESCRIPTION
**Pull request by alkino**

### CODE REVIEW

**Comment by tristan0x** [comment]
Can you add a test including this file?

**Comment by tdegeus** [comment]
My vote would be to also include H5Easy in this single include option

**Comment by alkino** [comment]
There already is `H5Easy.hpp` in the `H5.hpp`.

**Comment by tdegeus** [comment]
@alkino Sorry, missed that ☺️

**Comment by ferdonline** [comment]
I like this idea, but we should discuss it in detail before committing to any naming.
We should get ideas from existing projects.
Some things to consider: 
 - Having it top-level (not inside highfive/) so include could be just
  `#include HighFive.hpp`
- What headers to include by default. We should eventually have a good smaller set, so that we don't flood the compiler and complicate debugging.

**Comment by alkino** [comment]
> I like this idea, but we should discuss it in detail before committing to any naming.
> We should get ideas from existing projects.
> Some things to consider:
> 
>     * Having it top-level (not inside highfive/) so include could be just
>       `#include HighFive.hpp`
I'm not clear about that, is the include path `include` or `include/highfive`?
In cmake install script we do https://github.com/BlueBrain/HighFive/blob/master/CMake/PackageConfig.cmake#L3-L6
We should fix it to only one thing.
> 
>     * What headers to include by default. We should eventually have a good smaller set, so that we don't flood the compiler and complicate debugging.
I think we should include them all. This is the purpose of this single header, if we want to be more tuned, we can include all one by one.

**Comment by ferdonline** [comment]
> is the include path include or include/highfive

Include path shall be only "include". Client code should use `highfive/xxx.hpp` for specialized headers. That's why, alternatively we could have a single top-level header outside to not be confused with the lower-level ones.

**Comment by tristan0x** [comment]
> > is the include path include or include/highfive
> 
> Include path shall be only "include". Client code should use `highfive/xxx.hpp` for specialized headers. That's why, alternatively we could have a single top-level header outside to not be confused with the lower-level ones.

I agree with @ferdonline 
The single header should be top-level, not inside the `highfive/` directory.

Regarding the filename, I am ok with either `HighFive.hpp` (the project name), or `highfive.hpp` (consistent with the directory name).

**Comment by tristan0x** [comment]
> > ```
> > * What headers to include by default. We should eventually have a good smaller set, so that we don't flood the compiler and complicate debugging.
> > ```
> 
> 
> I think we should include them all. This is the purpose of this single header, if we want to be more tuned, we can include all one by one.

I agree with @alkino 
This all-in-one file should provide everything.

**Comment by alkino** [comment]
The problem is that include of single file is broken.
Let's try:

```#include <highfive/H5Group.hpp>

int main()
{
    return 0;
}```

```└▶ g++ tests_import.cpp $(pkg-config --cflags --libs hdf5) -I ./BUILD/FOO/usr/local/include/
In file included from ./BUILD/FOO/usr/local/include/highfive/H5Group.hpp:14:0,
                 from tests_import.cpp:1:
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits.hpp:39:25: error: ‘DataSetCreateProps’ does not name a type; did you mean ‘DataSetException’?
                   const DataSetCreateProps& createProps = DataSetCreateProps(),
                         ^~~~~~~~~~~~~~~~~~
                         DataSetException
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits.hpp:40:25: error: ‘DataSetAccessProps’ does not name a type; did you mean ‘DataSetException’?
                   const DataSetAccessProps& accessProps = DataSetAccessProps());
                         ^~~~~~~~~~~~~~~~~~
                         DataSetException
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits.hpp:55:25: error: ‘DataSetCreateProps’ does not name a type; did you mean ‘DataSetException’?
                   const DataSetCreateProps& createProps = DataSetCreateProps(),
                         ^~~~~~~~~~~~~~~~~~
                         DataSetException
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits.hpp:56:25: error: ‘DataSetAccessProps’ does not name a type; did you mean ‘DataSetException’?
                   const DataSetAccessProps& accessProps = DataSetAccessProps());
                         ^~~~~~~~~~~~~~~~~~
                         DataSetException
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits.hpp:71:25: error: ‘DataSetCreateProps’ does not name a type; did you mean ‘DataSetException’?
                   const DataSetCreateProps& createProps = DataSetCreateProps(),
                         ^~~~~~~~~~~~~~~~~~
                         DataSetException
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits.hpp:72:25: error: ‘DataSetAccessProps’ does not name a type; did you mean ‘DataSetException’?
                   const DataSetAccessProps& accessProps = DataSetAccessProps());
                         ^~~~~~~~~~~~~~~~~~
                         DataSetException
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits.hpp:81:15: error: ‘DataSetAccessProps’ does not name a type; did you mean ‘DataSetException’?
         const DataSetAccessProps& accessProps = DataSetAccessProps()) const;
               ^~~~~~~~~~~~~~~~~~
               DataSetException
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits.hpp:39:59: error: there are no arguments to ‘DataSetCreateProps’ that depend on a template parameter, so a declaration of ‘DataSetCreateProps’ must be available [-fpermissive]
                   const DataSetCreateProps& createProps = DataSetCreateProps(),
                                                           ^~~~~~~~~~~~~~~~~~
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits.hpp:39:59: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits.hpp:40:59: error: there are no arguments to ‘DataSetAccessProps’ that depend on a template parameter, so a declaration of ‘DataSetAccessProps’ must be available [-fpermissive]
                   const DataSetAccessProps& accessProps = DataSetAccessProps());
                                                           ^~~~~~~~~~~~~~~~~~
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits.hpp:55:59: error: there are no arguments to ‘DataSetCreateProps’ that depend on a template parameter, so a declaration of ‘DataSetCreateProps’ must be available [-fpermissive]
                   const DataSetCreateProps& createProps = DataSetCreateProps(),
                                                           ^~~~~~~~~~~~~~~~~~
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits.hpp:56:59: error: there are no arguments to ‘DataSetAccessProps’ that depend on a template parameter, so a declaration of ‘DataSetAccessProps’ must be available [-fpermissive]
                   const DataSetAccessProps& accessProps = DataSetAccessProps());
                                                           ^~~~~~~~~~~~~~~~~~
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits.hpp:71:59: error: there are no arguments to ‘DataSetCreateProps’ that depend on a template parameter, so a declaration of ‘DataSetCreateProps’ must be available [-fpermissive]
                   const DataSetCreateProps& createProps = DataSetCreateProps(),
                                                           ^~~~~~~~~~~~~~~~~~
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits.hpp:72:59: error: there are no arguments to ‘DataSetAccessProps’ that depend on a template parameter, so a declaration of ‘DataSetAccessProps’ must be available [-fpermissive]
                   const DataSetAccessProps& accessProps = DataSetAccessProps());
                                                           ^~~~~~~~~~~~~~~~~~
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits.hpp:81:49: error: there are no arguments to ‘DataSetAccessProps’ that depend on a template parameter, so a declaration of ‘DataSetAccessProps’ must be available [-fpermissive]
         const DataSetAccessProps& accessProps = DataSetAccessProps()) const;
                                                 ^~~~~~~~~~~~~~~~~~
In file included from ./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits.hpp:128:0,
                 from ./BUILD/FOO/usr/local/include/highfive/H5Group.hpp:14,
                 from tests_import.cpp:1:
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits_misc.hpp:40:43: error: ‘DataSetCreateProps’ does not name a type; did you mean ‘DataSetException’?
                                     const DataSetCreateProps& createProps,
                                           ^~~~~~~~~~~~~~~~~~
                                           DataSetException
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits_misc.hpp:41:43: error: ‘DataSetAccessProps’ does not name a type; did you mean ‘DataSetException’?
                                     const DataSetAccessProps& accessProps) {
                                           ^~~~~~~~~~~~~~~~~~
                                           DataSetException
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits_misc.hpp: In member function ‘HighFive::DataSet HighFive::NodeTraits<Derivate>::createDataSet(const string&, const HighFive::DataSpace&, const HighFive::DataType&, const int&, const int&)’:
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits_misc.hpp:45:57: error: request for member ‘getId’ in ‘createProps’, which is of non-class type ‘const int’
                                H5P_DEFAULT, createProps.getId(),
                                                         ^~~~~
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits_misc.hpp:46:44: error: request for member ‘getId’ in ‘accessProps’, which is of non-class type ‘const int’
                                accessProps.getId())) < 0) {
                                            ^~~~~
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits_misc.hpp: At global scope:
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits_misc.hpp:59:43: error: ‘DataSetCreateProps’ does not name a type; did you mean ‘DataSetException’?
                                     const DataSetCreateProps& createProps,
                                           ^~~~~~~~~~~~~~~~~~
                                           DataSetException
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits_misc.hpp:60:43: error: ‘DataSetAccessProps’ does not name a type; did you mean ‘DataSetException’?
                                     const DataSetAccessProps& accessProps) {
                                           ^~~~~~~~~~~~~~~~~~
                                           DataSetException
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits_misc.hpp:70:43: error: ‘DataSetCreateProps’ does not name a type; did you mean ‘DataSetException’?
                                     const DataSetCreateProps& createProps,
                                           ^~~~~~~~~~~~~~~~~~
                                           DataSetException
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits_misc.hpp:71:43: error: ‘DataSetAccessProps’ does not name a type; did you mean ‘DataSetException’?
                                     const DataSetAccessProps& accessProps) {
                                           ^~~~~~~~~~~~~~~~~~
                                           DataSetException
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits_misc.hpp:83:40: error: ‘DataSetAccessProps’ does not name a type; did you mean ‘DataSetException’?
                                  const DataSetAccessProps& accessProps) const {
                                        ^~~~~~~~~~~~~~~~~~
                                        DataSetException
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits_misc.hpp: In member function ‘HighFive::DataSet HighFive::NodeTraits<Derivate>::getDataSet(const string&, const int&) const’:
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits_misc.hpp:86:64: error: request for member ‘getId’ in ‘accessProps’, which is of non-class type ‘const int’
                              dataset_name.c_str(), accessProps.getId())) < 0) {
                                                                ^~~~~
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits_misc.hpp: In member function ‘HighFive::Group HighFive::NodeTraits<Derivate>::createGroup(const string&, bool)’:
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits_misc.hpp:95:60: error: return type ‘class HighFive::Group’ is incomplete
                                                bool parents) {
                                                            ^
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits_misc.hpp:96:5: error: ‘RawPropertyList’ was not declared in this scope
     RawPropertyList<PropertyType::LINK_CREATE> lcpl;
     ^~~~~~~~~~~~~~~
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits_misc.hpp:96:21: error: ‘PropertyType’ has not been declared
     RawPropertyList<PropertyType::LINK_CREATE> lcpl;
                     ^~~~~~~~~~~~
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits_misc.hpp:96:48: error: ‘lcpl’ was not declared in this scope
     RawPropertyList<PropertyType::LINK_CREATE> lcpl;
                                                ^~~~
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits_misc.hpp:96:48: note: suggested alternative: ‘logl’
     RawPropertyList<PropertyType::LINK_CREATE> lcpl;
                                                ^~~~
                                                logl
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits_misc.hpp:100:11: error: ‘group’ has incomplete type
     Group group;
           ^~~~~
In file included from ./BUILD/FOO/usr/local/include/highfive/H5Group.hpp:13:0,
                 from tests_import.cpp:1:
./BUILD/FOO/usr/local/include/highfive/bits/H5Annotate_traits.hpp:18:7: note: forward declaration of ‘class HighFive::Group’
 class Group;
       ^~~~~
In file included from ./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits.hpp:128:0,
                 from ./BUILD/FOO/usr/local/include/highfive/H5Group.hpp:14,
                 from tests_import.cpp:1:
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits_misc.hpp: In member function ‘HighFive::Group HighFive::NodeTraits<Derivate>::getGroup(const string&) const’:
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits_misc.hpp:112:63: error: return type ‘class HighFive::Group’ is incomplete
 NodeTraits<Derivate>::getGroup(const std::string& group_name) const {
                                                               ^~~~~
./BUILD/FOO/usr/local/include/highfive/bits/H5Node_traits_misc.hpp:113:11: error: ‘group’ has incomplete type
     Group group;
           ^~~~~
In file included from ./BUILD/FOO/usr/local/include/highfive/H5Group.hpp:13:0,
                 from tests_import.cpp:1:
./BUILD/FOO/usr/local/include/highfive/bits/H5Annotate_traits.hpp:18:7: note: forward declaration of ‘class HighFive::Group’
 class Group;
       ^~~~~```

There is a specific order to include things.

**Comment by tdegeus** [comment]
@alkino I would say that that is a bug, and not an argument to have a single header include. I.e. I think that `H5Group.hpp` should include all the headers it needs.

**Comment by alkino** [comment]
About performance, including explicitly `H5File.hpp` and `H5Group.hpp` include implicitly:
```
 H5Attribute.hpp
 H5DataSet.hpp
 H5DataSpace.hpp
 H5DataType.hpp
 H5Exception.hpp
 H5File.hpp
 H5FileDriver.hpp
 H5Group.hpp
 H5Object.hpp
 H5PropertyList.hpp
 H5Selection.hpp
 H5Utility.hpp
 bits/H5Annotate_traits.hpp
 bits/H5Annotate_traits_misc.hpp
 bits/H5Attribute_misc.hpp
 bits/H5Converter_misc.hpp
 bits/H5DataSet_misc.hpp
 bits/H5DataType_misc.hpp
 bits/H5Dataspace_misc.hpp
 bits/H5Exception_misc.hpp
 bits/H5FileDriver_misc.hpp
 bits/H5File_misc.hpp
 bits/H5Group_misc.hpp
 bits/H5Iterables_misc.hpp
 bits/H5Node_traits.hpp
 bits/H5Node_traits_misc.hpp
 bits/H5Object_misc.hpp
 bits/H5PropertyList_misc.hpp
 bits/H5Selection_misc.hpp
 bits/H5Slice_traits.hpp
 bits/H5Slice_traits_misc.hpp
 bits/H5Utils.hpp
```
There is only `H5Easy*` missing.

**Comment by alkino** [comment]
Here is a little diagram of header dependecies. The boxes are public, others are private.
a

**Comment by ferdonline** [comment]
The issue you'r solving here (#103) you'r already fixing in #225. That indeed should be solved. I would like to know the opinion of @tristan0x to that solution, as I'm indifferent. I have the little impression that those files shouldn't move as they declare users classes, but on the other hand, true that the user shouldn't import them... Maybe someone with more experience in header-only complex codes can help.

Second though. The last commit removes the linking with mpi libs. As discussed in #219 we should still link with them. I'm also ok with you want to make it part of the public interface of HighFive so that everything that uses HighFive gets those flags

**Comment by alkino** [comment]
We cancel this way.

**Comment by ferdonline** [comment]
As some others commented here, I agree that it's not really worth to have the single include.
Once the issue is fixed by #225 there is no major reason to have it.
It is true that "File" will include most of the other components, but some of them are still decoupled.

**Pull request closed without merging**
