### PR TITLE
Fixing CI - switched to correct Conda channel

### PR DESCRIPTION
**Pull request by tdegeus**
The QuantStack channel on conda was merged into the conda-forge channel. The QuantStack channel was removed: trying to use it results in an error: https://travis-ci.org/BlueBrain/HighFive

### CODE REVIEW

**Comment by ferdonline** [comment]
@tdegeus could you please add some description for us to understand better the need for this change?

**Comment by tdegeus** [comment]
@ferdonline The `QuantStack` channel on conda was merged into the `conda-forge` channel. The `QuantStack` channel was removed.

**Comment by ferdonline** [comment]
Thanks. That info is important in the description of the PR, it’s really not nice to crawl history and see “emptyness”. Would you mind adding it there?

**Comment by tdegeus** [comment]
@ferdonline Done. Can you re-trigger Travis, it has one of its random initialisation fails.

**Comment by ferdonline** [comment]
please retest

**Comment by ferdonline** [comment]
retest this please

**Comment by tdegeus** [comment]
@ferdonline Since you have access you can simply retrigger the CI (https://stackoverflow.com/a/17624403/2646505), I can't. I have worked around by pushing an empty commit.

**Comment by ferdonline** [comment]
I'm afraid it won't update the status here...

**Comment by ferdonline** [comment]
Thanks!

**Pull request merged**
